# Generated by Django 2.2.4 on 2019-08-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Russian', max_length=20),
            preserve_default=False,
        ),
    ]
