# Generated by Django 2.2.4 on 2019-08-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190815_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
