# Generated by Django 2.2.4 on 2019-08-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_book_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
